### ISSUE TITLE
Remove duplicate photo display

### ISSUE THREAD

**Issue by taylorsweetman** [NoBullAuthenticity/No-Bull-MVP-#3]
Under the "live" photo, there are two elements which each contain an image of the last picture taken. One is a `canvas` element, and the other is an `img` element wrapped in a `div`.

**Comment by NoBullAuthenticity** [comment]
Is this the bug you're referring to? Was wondering why there were 2 boxes instead of one... 

     <div class="output">
        <img id="photo" alt="The screen capture will appear in this box." />
      </div>

**Comment by taylorsweetman** [comment]
> Is this the bug you're referring to? Was wondering why there were 2 boxes instead of one...
> 
> ```
>  <div class="output">
>     <img id="photo" alt="The screen capture will appear in this box." />
>   </div>
> ```

Yep you nailed it! Removed this div in #4
